import { Inter } from 'next/font/google';
import './globals.css';

import { ContextModal } from '@/context/ContextModal';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <ContextModal>
          {children}
          <ToastContainer autoClose={500} />
        </ContextModal>
      </body>
    </html>
  );
}
